name: CI

on:
  push:
    branches: [master, alpha, beta]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [master, alpha, beta]
    paths-ignore:
      - '**/*.md'

jobs:

  sanity:
    name: Sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install main project
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Lint
        run: npm run lint:ci
      - name: Unit Tests
        run: npm test
      - name: Pack
        run: npm pack
      - name: E2E Tests
        run: npm run test:e2e
      - name: Install package-e2e project
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: 'package-e2e'
      - name: Packaging E2E Tests
        run: npm test
        working-directory: 'package-e2e'

  publish:
    name: Publish
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
    needs: [sanity]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install main project
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Semantic release
        run: npx --no-install semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
